//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFNanoGui.NanoVisualizerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NanoVisualizerService.IVisualizerService")]
    public interface IVisualizerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisualizerService/uploadCubeFile", ReplyAction="http://tempuri.org/IVisualizerService/uploadCubeFileResponse")]
        System.Guid uploadCubeFile(System.IO.Stream inpFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisualizerService/visualizeCubeFile", ReplyAction="http://tempuri.org/IVisualizerService/visualizeCubeFileResponse")]
        System.IO.Stream visualizeCubeFile(System.Guid fid, System.Collections.Generic.Dictionary<string, string> param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IVisualizerServiceChannel : WCFNanoGui.NanoVisualizerService.IVisualizerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class VisualizerServiceClient : System.ServiceModel.ClientBase<WCFNanoGui.NanoVisualizerService.IVisualizerService>, WCFNanoGui.NanoVisualizerService.IVisualizerService {
        
        public VisualizerServiceClient() {
        }
        
        public VisualizerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisualizerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisualizerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisualizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid uploadCubeFile(System.IO.Stream inpFile) {
            return base.Channel.uploadCubeFile(inpFile);
        }
        
        public System.IO.Stream visualizeCubeFile(System.Guid fid, System.Collections.Generic.Dictionary<string, string> param) {
            return base.Channel.visualizeCubeFile(fid, param);
        }
    }
}
